version: '3'

services:
  mysql:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 30s
      retries: 5
      start_period: 600s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=oboshkodatabase
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060

  backend:
    build: backend
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app
    command: /app/app.py
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=/run/secrets/db-password
      - MYSQL_DB=oboshkodatabase
    secrets:
      - db-password
    ports:
      - 8000:8000
    networks:
      - backnet
      - frontnet
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: frontend
    restart: always
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/share/nginx/html/
    depends_on: 
      - backend
    networks:
      - frontnet

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
  frontnet: